spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell
  port: 8080
wechat:
  mpAppId: wxf664b92c64d30d27
  mpAppSecret: 41f7b835ff67b3c84b377a8f222de2b2
  mchId: 12345
  mchKey: 123
  keyPath: 12321312
  notifyUrl: http://wmd.mynatapp.cc/sell/pay/notify

  #wechat:
  #  mp-appId: wxf46e4e2240563ed2
  #  mp-appSecret: 33f59d78904cd8cd9921bc6fd4b58eab
  #  mch-id: 12345
  #  mch-key: 123
  #  key-path: 12321312
  #  notify-url: 21312321